version: '3.8'
services:
  client_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}:/app
      - ${PWD}/node_modules:/app/node_modules
    stdin_open: true
    tty: true